---
- name: Create database
  command: psql -h localhost -U postgres -f /opt/hds/sql/ciofuserdb.create.sql

- name: Create tables
  command: psql -h localhost -U postgres -f /opt/hds/sql/ciofuserdb.init.sql ciofuserdb
